sudo: required
dist: trusty
language: rust

matrix:
  fast_finish: false
  include:
  - rust: stable

cache:
  apt: true
  directories:
  - $TRAVIS_BUILD_DIR/target
  - $HOME/.cargo

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-4.0
    packages:
    - libboost-dev
    - clang-4.0

script:
  - cargo test --all
  - cargo build --release
  - cargo bench --all

env:
  global:
  - RUST_BACKTRACE=1
  - CC="clang-4.0"
