sudo: required
dist: trusty
language: rust
matrix:
  fast_finish: false
  include:
  - rust: stable
cache:
  apt: true
  directories:
  - $TRAVIS_BUILD_DIR/target
  - $HOME/.cargo
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libboost-dev
script:
  - cargo test --verbose --all
  - cargo build --release
  - cargo bench --verbose --all
env:
  global:
  - RUST_BACKTRACE=1
